language: php

dist: xenial

services:
  - mysql
  - postgresql


cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_ROOT_VERSION="2.x-dev"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.2
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PDO=1 PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=1

before_script:
# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer require --no-update silverstripe/recipe-cms:5.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:3.x-dev; fi
  - if [[ $DB == SQLITE ]]; then composer require --no-update silverstripe/sqlite3:3.x-dev; fi
  - if [[ $PHPCS_TEST ]]; then composer require squizlabs/php_codesniffer:^3 --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml -vvv; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
